### ISSUE TITLE
Lowest dependency of R>4.1?

### ISSUE THREAD

**Issue by xlucpu** [grisslab/scClassifR#5]
The newest R version is 4.0.4 (R version 4.0.4 (Lost Library Book) has been released on 2021-02-15), so how can I install this package since the dependency needs an R>4.1?

Best.

**Comment by yulijia** [comment]
You need to download this package, and fix the DESCRIPTION file, line 30, https://github.com/grisslab/scClassifR/blob/master/DESCRIPTION#L30
`R (>= 4.1)` to `R (>= 4.0)`

Then install the modified package from local.

**Comment by jgriss** [comment]
Hi @xlucpu 

This has now been fixed. If you try to install the package from GitHub again, everything should work fine.

Kind regards,
Johannes
