### ISSUE TITLE
error in simplify_prediction 

### ISSUE THREAD

**Issue by xiebb123456** [grisslab/scClassifR#7]
Hi,

There is a bug in support.R line 695.

max_clf <- gsub('_p', '', max_p)    -->   max_clf <- gsub('_p$', '', max_p)  

this would cause error, if the words in cell type begin with 'p' like 'kidney_proximal_straight_tubule_epithelial_cell_p' can not find the right classifer.

**Comment by jgriss** [comment]
Hi @xiebb123456,

Thanks a lot for reporting this bug. It's now fixed in 0d423bc and will be available on BioConductor shortly.

Kind regards,
Johannes
