### ISSUE TITLE
Error: invalid 'nrow' value (too large or NA)

### ISSUE THREAD

**Issue by monikaramos** [grisslab/scClassifR#9]
Hi there, I am attempting to run this package on my own Seurat object (size = 1.1GB) and am getting the following error: 

"Error in matrix(NA, nrow(newdata) * length(kernlab::lev(modelFit)), ncol = length(kernlab::lev(modelFit))) : 
  invalid 'nrow' value (too large or NA)
In addition: Warning message:
In method$prob(modelFit = modelFit, newdata = newdata, submodels = param) :
 
 Error in matrix(NA, nrow(newdata) * length(kernlab::lev(modelFit)), ncol = length(kernlab::lev(modelFit))) : 
  invalid 'nrow' value (too large or NA) "

It ran fine on the example data but I see that someone else has posted about this same error regarding size. 

Has this been fixed or are there additional parameters I need to specify? I'd really like to use this package for cell type classification...

Thanks in advance.

**Comment by jgriss** [comment]
Hi @monikaramos 

Thanks a lot for reporting this issue!

We are currently in the process of retiring this package. The current version had to be renamed is now available here: [scAnnotatR](https://github.com/grisslab/scAnnotatR).

**Comment by monikaramos** [comment]
Hi @jgriss ,

Thank you for the quick response. Is the new version, "scAnnotatR", no longer experiencing the described error?

**Comment by jgriss** [comment]
Hi @monikaramos 

Yes, I believe that this issue should be fixed

**Comment by nttvy** [comment]
Hi @monikaramos 

We believe this problem happens from caret and kernlab, two of our dependencies. This error seems to occur with the weak trained models, so it cannot give class prediction probability. For more information: [here](https://github.com/topepo/caret/issues/809) 

To solve this, you can try changing the seed before training the models, or even changing the set of features. However, we still recommend you to use our new package as mentioned above. 

Bests,
Vy
